# Generated by Django 5.1.5 on 2025-01-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profileuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
