# Generated by Django 5.1.5 on 2025-02-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profileuser_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
