# Generated by Django 5.1.5 on 2025-02-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profileuser_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='cropping_photo',
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog/profile image/', verbose_name='photo'),
        ),
    ]
