# Generated by Django 5.1.5 on 2025-03-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_profileuser_cropping_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
