

services:
  rabbitmq:
    image: rabbitmq:3.9
    networks:
      - main
    ports:
      - "YOUR POSTS"
    restart: always

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_DB=YOUR DBNAME
      - POSTGRES_USER=YOUR USERNAME
      - POSTGRES_PASSWORD=YOUR PASSWORD
    networks:
      - main
    ports:
      - "YOUR POSTS"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery_worker:
    container_name: celery_worker
    command: "celery -A freeWords worker -l info"
    depends_on:
      - app
      - rabbitmq
      - postgres
    build: .
    environment:
      - C_FORCE_ROOT="true"
    networks:
      - main
    restart: always

  redis:
    image: redis:6.2
    ports:
      - "YOUR PORTS"
    networks:
      - main
    restart: always

  app:
    build: .
    command: >
      bash -c "python manage.py collectstatic --noinput && python manage.py migrate && exec gunicorn freeWords.wsgi:application --bind 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/app/
    depends_on:
      - postgres
      - rabbitmq
      - redis
    ports:
      - "YOUR PORTS"
    networks:
      - main
    restart: always

networks:
  main:

volumes:
  postgres_data:
