

services:
  rabbitmq:
    image: rabbitmq:latest
    networks:
      - main
    ports:
      - "5672:5672"
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=freewords
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    networks:
      - main
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery_worker:
    container_name: celery_worker
    command: "celery -A freeWords worker -l info"
    depends_on:
      - app
      - rabbitmq
      - postgres
    build: .
    environment:
      - C_FORCE_ROOT="true"
    networks:
      - main
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - main
    restart: always

  app:
    build: .
    command: >
      bash -c "python manage.py migrate && exec gunicorn freeWords.wsgi:application --bind 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/app/
      - ./freeWords/static:/app/freeWords/static
      - ./staticfiles:/app/staticfiles
    depends_on:
      - postgres
      - rabbitmq
      - redis
    ports:
      - "8000:8000"
    networks:
      - main
    restart: always

networks:
  main:

volumes:
  postgres_data:
