# Generated by Django 5.1.5 on 2025-01-24 13:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_heading', models.CharField(max_length=250)),
                ('title_description', models.CharField(max_length=250)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/cover_image/', verbose_name='Cover Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'BlogPosts',
                'ordering': ['-created_at'],
            },
        ),
    ]
