# Generated by Django 5.1.5 on 2025-01-24 13:10

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_description',
            field=models.CharField(max_length=250, verbose_name='Title Description'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_heading',
            field=models.CharField(max_length=250, verbose_name='Title Heading'),
        ),
    ]
