# Generated by Django 5.1.5 on 2025-01-24 13:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blogpost_options_alter_blogpost_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'BlogPosts'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_heading',
            field=models.CharField(max_length=250),
        ),
    ]
