# Generated by Django 5.1.5 on 2025-01-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blogpost_options_alter_blogpost_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='null', max_length=250),
        ),
    ]
