# Generated by Django 5.1.5 on 2025-01-30 10:21

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_blogpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cropping_ci',
            field=image_cropping.fields.ImageRatioField('cover_image', '700x220', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping ci'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='blog/cover_image/', verbose_name='Cover Image'),
        ),
    ]
