# Generated by Django 5.1.5 on 2025-02-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_blogpost_cropping_ci_alter_blogpost_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/cover_image/', verbose_name='Cover Image'),
        ),
    ]
