# Generated by Django 5.1.5 on 2025-02-06 14:56

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_blogpost_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='blog/cover_image/', verbose_name='Cover Image'),
        ),
    ]
