# Generated by Django 5.1.5 on 2025-02-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_blogpost_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='cropping_ci',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/cover_image/', verbose_name='Cover Image'),
        ),
    ]
