# Generated by Django 5.1.5 on 2025-02-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_blogpost_cropping_ci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
