# Generated by Django 5.1.5 on 2025-02-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_blogpost_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='view',
        ),
    ]
